package br.gov.mt.sefaz.itc.model.tabelabasica.ajuda.cargainicial;

public interface TelasAjuda
{
	//TABELAS BÁSICAS
	//BEM
	public static final String TELA_BEM_INCLUIR = "DADOS DO REGISTRO - BENS INCLUIR";
	public static final String TELA_BEM_ALTERAR = "DADOS DO REGISTRO - BENS ALTERAR";
	public static final String TELA_BEM_CONSULTAR = "FILTRO PARA PESQUISA - BENS CONSULTAR";
	
	public static final int CODIGO_TELA_BEM_INCLUIR = 1;
	public static final int CODIGO_TELA_BEM_ALTERAR = 2;
	public static final int CODIGO_TELA_BEM_CONSULTAR = 3;
	
	//CULTURA
	public static final String TELA_CULTURA_INCLUIR = "DADOS DO REGISTRO - CULTURA INCLUIR";
	public static final String TELA_CULTURA_ALTERAR = "DADOS DO REGISTRO - CULTURA ALTERAR";
	public static final String TELA_CULTURA_CONSULTAR = "FILTRO PARA PESQUISA - CULTURA CONSULTAR";
	
	public static final int CODIGO_TELA_CULTURA_INCLUIR = 4;
	public static final int CODIGO_TELA_CULTURA_ALTERAR = 5;
	public static final int CODIGO_TELA_CULTURA_CONSULTAR = 6;
	
	//REBANHO
	public static final String TELA_REBANHO_INCLUIR = "DADOS DO REGISTRO - REBANHO INCLUIR";
	public static final String TELA_REBANHO_ALTERAR = "DADOS DO REGISTRO - REBANHO ALTERAR";
	public static final String TELA_REBANHO_CONSULTAR = "FILTRO PARA PESQUISA - REBANHO CONSULTAR";
	
	public static final int CODIGO_TELA_REBANHO_INCLUIR = 7;
	public static final int CODIGO_TELA_REBANHO_ALTERAR = 8;
	public static final int CODIGO_TELA_REBANHO_CONSULTAR = 9;
	
	//NATUREZA DA OPERAÇÃO
	public static final String TELA_NATUREZA_OPERACAO_INCLUIR = "DADOS DO REGISTRO - NATUREZA OPERAÇÃO INCLUIR";
	public static final String TELA_NATUREZA_OPERACAO_ALTERAR = "DADOS DO REGISTRO - NATUREZA OPERAÇÃO ALTERAR";
	public static final String TELA_NATUREZA_OPERACAO_CONSULTAR = "RESULTADOS DA PESQUISA - NATUREZA OPERAÇÃO CONSULTAR";
	
	public static final int CODIGO_TELA_NATUREZA_OPERACAO_INCLUIR = 10;
	public static final int CODIGO_TELA_NATUREZA_OPERACAO_ALTERAR = 11;
	public static final int CODIGO_TELA_NATUREZA_OPERACAO_CONSULTAR = 12;
	
	//CONFIGURAÇÃO GERENCIAL DE PARÂMETROS
	public static final String TELA_CONFIGURACAO_GERENCIAL_ALTERAR = "DADOS DO REGISTRO - CONFIGURAÇÃO GERENCIAL DE PARÂMETROS ALTERAR";

	public static final int CODIGO_TELA_CONFIGURACAO_GERENCIAL_ALTERAR = 13;

	//BENFEITORIA
	public static final String TELA_BENFEITORIA_INCLUIR = "DADOS DO REGISTRO - BENFEITORIA INCLUIR";
	public static final String TELA_BENFEITORIA_ALTERAR = "DADOS DO REGISTRO - BENFEITORIA ALTERAR";
	public static final String TELA_BENFEITORIA_CONSULTAR = "RESULTADOS DA PESQUISA - BENFEITORIA CONSULTAR";
	
	public static final int CODIGO_TELA_BENFEITORIA_INCLUIR = 14;
	public static final int CODIGO_TELA_BENFEITORIA_ALTERAR = 15;
	public static final int CODIGO_TELA_BENFEITORIA_CONSULTAR = 16;
	
	//CONSTRUÇÃO
	public static final String TELA_CONSTRUCAO_INCLUIR = "DADOS DO REGISTRO - CONSTRUÇÃO INCLUIR";
	public static final String TELA_CONSTRUCAO_ALTERAR = "DADOS DO REGISTRO - CONSTRUÇÃO ALTERAR";
	public static final String TELA_CONSTRUCAO_CONSULTAR = "RESULTADOS DA PESQUISA - CONSTRUÇÃO CONSULTAR";
	
	public static final int CODIGO_TELA_CONSTRUCAO_INCLUIR = 17;
	public static final int CODIGO_TELA_CONSTRUCAO_ALTERAR = 18;
	public static final int CODIGO_TELA_CONSTRUCAO_CONSULTAR = 19;
	
	//PARAMETROS DA LEGISLAÇÃO
	public static final String TELA_PARAMETRO_LEGISLACAO_INCLUIR = "DADOS DO REGISTRO - PARÂMETROS DE LEGISLAÇÃO INCLUIR";
	public static final String TELA_PARAMETRO_LEGISLACAO_ALTERAR = "DADOS DO REGISTRO - PARÂMETROS DE LEGISLAÇÃO ALTERAR";
	public static final String TELA_PARAMETRO_LEGISLACAO_CONSULTAR = "RESULTADOS DA PESQUISA - PARÂMETROS DE LEGISLAÇÃO CONSULTAR";

	public static final int CODIGO_TELA_PARAMETRO_LEGISLACAO_INCLUIR = 20;
	public static final int CODIGO_TELA_PARAMETRO_LEGISLACAO_ALTERAR = 21;
	public static final int CODIGO_TELA_PARAMETRO_LEGISLACAO_CONSULTAR = 22;
	
	//AJUDA
	public static final String TELA_AJUDA_INCLUIR = "DADOS DO REGISTRO - AJUDA INCLUIR";
	public static final String TELA_AJUDA_ALTERAR = "DADOS DO REGISTRO - AJUDA ALTERAR";
	public static final String TELA_AJUDA_CONSULTAR = "RESULTADOS DA PESQUISA - AJUDA CONSULTAR";
	
	public static final int CODIGO_TELA_AJUDA_INCLUIR = 23;
	public static final int CODIGO_TELA_AJUDA_ALTERAR = 24;
	public static final int CODIGO_TELA_AJUDA_CONSULTAR = 25;
	
	
	//GIA-ITCD
	//INVENTARIO ARROLAMENTO
	//INCLUIR
	public static final String TELA_GIA_INVENTARIO_DADOS_GERAIS_INCLUIR = "INVENTÁRIO/ARROLAMENTO - DADOS GERAIS INCLUIR";
	public static final String TELA_GIA_INVENTARIO_BEM_TRIBUTAVEL_INCLUIR = "INVENTÁRIO/ARROLAMENTO - BENS TRIBUTÁVEIS INCLUIR";
	public static final String TELA_GIA_INVENTARIO_BEM_TRIBUTAVEL_IMOVEL_RURAL_INCLUIR = "INVENTÁRIO/ARROLAMENTO - IMÓVEL RURAL INCLUIR";
	public static final String TELA_GIA_INVENTARIO_BEM_TRIBUTAVEL_IMOVEL_URBANO_INCLUIR = "INVENTÁRIO/ARROLAMENTO - IMÓVEL URBANO INCLUIR";
	public static final String TELA_GIA_INVENTARIO_BENEFICIARIO_INCLUIR = "INVENTÁRIO/ARROLAMENTO - BENEFICIÁRIO INCLUIR";

	public static final int CODIGO_TELA_GIA_INVENTARIO_DADOS_GERAIS_INCLUIR = 26;
	public static final int CODIGO_TELA_GIA_INVENTARIO_BEM_TRIBUTAVEL_INCLUIR = 27;
	public static final int CODIGO_TELA_GIA_INVENTARIO_BEM_TRIBUTAVEL_IMOVEL_RURAL_INCLUIR = 28;
	public static final int CODIGO_TELA_GIA_INVENTARIO_BEM_TRIBUTAVEL_IMOVEL_URBANO_INCLUIR = 29;
	public static final int CODIGO_TELA_GIA_INVENTARIO_BENEFICIARIO_INCLUIR = 30;
	
	//ALTERAR
	public static final String TELA_GIA_INVENTARIO_DADOS_GERAIS_ALTERAR = "INVENTÁRIO/ARROLAMENTO - DADOS GERAIS ALTERAR";
	public static final String TELA_GIA_INVENTARIO_BEM_TRIBUTAVEL_ALTERAR = "INVENTÁRIO/ARROLAMENTO - BENS TRIBUTÁVEIS ALTERAR";
	public static final String TELA_GIA_INVENTARIO_BEM_TRIBUTAVEL_IMOVEL_RURAL_ALTERAR = "INVENTÁRIO/ARROLAMENTO - IMÓVEL RURAL ALTERAR";
	public static final String TELA_GIA_INVENTARIO_BEM_TRIBUTAVEL_IMOVEL_URBANO_ALTERAR = "INVENTÁRIO/ARROLAMENTO - IMÓVEL URBANO ALTERAR";
	public static final String TELA_GIA_INVENTARIO_BENEFICIARIO_ALTERAR = "INVENTÁRIO/ARROLAMENTO - BENEFICIÁRIO ALTERAR";

	public static final int CODIGO_TELA_GIA_INVENTARIO_DADOS_GERAIS_ALTERAR = 31;
	public static final int CODIGO_TELA_GIA_INVENTARIO_BEM_TRIBUTAVEL_ALTERAR = 32;
	public static final int CODIGO_TELA_GIA_INVENTARIO_BEM_TRIBUTAVEL_IMOVEL_RURAL_ALTERAR = 33;
	public static final int CODIGO_TELA_GIA_INVENTARIO_BEM_TRIBUTAVEL_IMOVEL_URBANO_ALTERAR = 34;
	public static final int CODIGO_TELA_GIA_INVENTARIO_BENEFICIARIO_ALTERAR = 35;
	
	//GERAIS	
	public static final String TELA_GIA_INVENTARIO_DEMONSTRATIVO_CALCULO = "INVENTÁRIO/ARROLAMENTO - DEMONSTRATIVO DE CÁLCULO";
	public static final String TELA_GIA_INVENTARIO_DEMONSTRATIVO_CALCULO_CONSULTAR = "INVENTÁRIO/ARROLAMENTO - DEMONSTRATIVO DE CÁLCULO CONSULTAR";
	public static final String TELA_GIA_INVENTARIO_SENHA_CADASTRAR = "INVENTÁRIO/ARROLAMENTO - CADASTRAR SENHA";
	public static final String TELA_GIA_INVENTARIO_CONTRIBUINTE_SELECIONAR = "INVENTÁRIO/ARROLAMENTO - CONTRIBUINTE SELECIONAR";

	public static final int CODIGO_TELA_GIA_INVENTARIO_DEMONSTRATIVO_CALCULO = 36;
	public static final int CODIGO_TELA_GIA_INVENTARIO_DEMONSTRATIVO_CALCULO_CONSULTAR = 37;
	public static final int CODIGO_TELA_GIA_INVENTARIO_SENHA_CADASTRAR = 38;
	public static final int CODIGO_TELA_GIA_INVENTARIO_CONTRIBUINTE_SELECIONAR = 39;

	
	//DOAÇÃO
	//INCLUIR
	public static final String TELA_GIA_DOACAO_DADOS_GERAIS_INCLUIR = "DOAÇÃO - DADOS GERAIS INCLUIR";
	public static final String TELA_GIA_DOACAO_BEM_TRIBUTAVEL_INCLUIR = "DOAÇÃO - BENS TRIBUTÁVEIS INCLUIR";
	public static final String TELA_GIA_DOACAO_BEM_TRIBUTAVEL_IMOVEL_RURAL_INCLUIR = "DOAÇÃO - IMÓVEL RURAL INCLUIR";
	public static final String TELA_GIA_DOACAO_BEM_TRIBUTAVEL_IMOVEL_URBANO_INCLUIR = "DOAÇÃO - IMÓVEL URBANO INCLUIR";
	public static final String TELA_GIA_DOACAO_BENEFICIARIO_INCLUIR = "DOAÇÃO - BENEFICIÁRIO INCLUIR";

	public static final int CODIGO_TELA_GIA_DOACAO_DADOS_GERAIS_INCLUIR = 40;
	public static final int CODIGO_TELA_GIA_DOACAO_BEM_TRIBUTAVEL_INCLUIR = 41;
	public static final int CODIGO_TELA_GIA_DOACAO_BEM_TRIBUTAVEL_IMOVEL_RURAL_INCLUIR = 42;
	public static final int CODIGO_TELA_GIA_DOACAO_BEM_TRIBUTAVEL_IMOVEL_URBANO_INCLUIR = 43;
	public static final int CODIGO_TELA_GIA_DOACAO_BENEFICIARIO_INCLUIR = 44;
	 
	//ALTERAR
	public static final String TELA_GIA_DOACAO_DADOS_GERAIS_ALTERAR = "DOAÇÃO - DADOS GERAIS ALTERAR";
	public static final String TELA_GIA_DOACAO_BEM_TRIBUTAVEL_ALTERAR = "DOAÇÃO - BENS TRIBUTÁVEIS ALTERAR";
	public static final String TELA_GIA_DOACAO_BEM_TRIBUTAVEL_IMOVEL_RURAL_ALTERAR = "DOAÇÃO - IMÓVEL RURAL ALTERAR";
	public static final String TELA_GIA_DOACAO_BEM_TRIBUTAVEL_IMOVEL_URBANO_ALTERAR = "DOAÇÃO - IMÓVEL URBANO ALTERAR";
	public static final String TELA_GIA_DOACAO_BENEFICIARIO_ALTERAR = "DOAÇÃO - BENEFICIÁRIO ALTERAR";

	public static final int CODIGO_TELA_GIA_DOACAO_DADOS_GERAIS_ALTERAR = 45;
	public static final int CODIGO_TELA_GIA_DOACAO_BEM_TRIBUTAVEL_ALTERAR = 46;
	public static final int CODIGO_TELA_GIA_DOACAO_BEM_TRIBUTAVEL_IMOVEL_RURAL_ALTERAR = 47;
	public static final int CODIGO_TELA_GIA_DOACAO_BEM_TRIBUTAVEL_IMOVEL_URBANO_ALTERAR = 48;
	public static final int CODIGO_TELA_GIA_DOACAO_BENEFICIARIO_ALTERAR = 49;
	 
	//GERAIS 
	public static final String TELA_GIA_DOACAO_DEMONSTRATIVO_CALCULO = "DOAÇÃO - DEMONSTRATIVO DE CÁLCULO";
	public static final String TELA_GIA_DOACAO_DEMONSTRATIVO_CALCULO_CONSULTAR = "DOAÇÃO - DEMONSTRATIVO DE CÁLCULO CONSULTAR";
	public static final String TELA_GIA_DOACAO_SENHA_CADASTRAR = "DOAÇÃO - CADASTRAR SENHA";
	public static final String TELA_GIA_DOACAO_CONTRIBUINTE_SELECIONAR = "DOAÇÃO - CONTRIBUINTE SELECIONAR";
	
	public static final int CODIGO_TELA_GIA_DOACAO_DEMONSTRATIVO_CALCULO = 50;
	public static final int CODIGO_TELA_GIA_DOACAO_DEMONSTRATIVO_CALCULO_CONSULTAR = 51;
	public static final int CODIGO_TELA_GIA_DOACAO_SENHA_CADASTRAR = 52;
	public static final int CODIGO_TELA_GIA_DOACAO_CONTRIBUINTE_SELECIONAR = 53;


	//SEPARAÇÃO/DIVÓRCIO/PARTILHA
	//INCLUIR
	public static final String TELA_GIA_SEPARACAO_DADOS_GERAIS_INCLUIR = "SEPARAÇÃO/DIVÓRCIO/PARTILHA - DADOS GERAIS INCLUIR";
	public static final String TELA_GIA_SEPARACAO_BEM_TRIBUTAVEL_INCLUIR = "SEPARAÇÃO/DIVÓRCIO/PARTILHA - BENS TRIBUTÁVEIS INCLUIR";
	public static final String TELA_GIA_SEPARACAO_BEM_TRIBUTAVEL_IMOVEL_RURAL_INCLUIR = "SEPARAÇÃO/DIVÓRCIO/PARTILHA - IMÓVEL RURAL INCLUIR";
	public static final String TELA_GIA_SEPARACAO_BEM_TRIBUTAVEL_IMOVEL_URBANO_INCLUIR = "SEPARAÇÃO/DIVÓRCIO/PARTILHA - IMÓVEL URBANO INCLUIR";
	public static final String TELA_GIA_SEPARACAO_CONJUGE_INCLUIR = "SEPARAÇÃO/DIVÓRCIO/PARTILHA - CONJUGE INCLUIR";

	public static final int CODIGO_TELA_GIA_SEPARACAO_DADOS_GERAIS_INCLUIR = 54;
	public static final int CODIGO_TELA_GIA_SEPARACAO_BEM_TRIBUTAVEL_INCLUIR = 55;
	public static final int CODIGO_TELA_GIA_SEPARACAO_BEM_TRIBUTAVEL_IMOVEL_RURAL_INCLUIR = 56;
	public static final int CODIGO_TELA_GIA_SEPARACAO_BEM_TRIBUTAVEL_IMOVEL_URBANO_INCLUIR = 57;
	public static final int CODIGO_TELA_GIA_SEPARACAO_CONJUGE_INCLUIR = 58;
	 
	//ALTERAR
	public static final String TELA_GIA_SEPARACAO_DADOS_GERAIS_ALTERAR = "SEPARAÇÃO/DIVÓRCIO/PARTILHA - DADOS GERAIS ALTERAR";
	public static final String TELA_GIA_SEPARACAO_BEM_TRIBUTAVEL_ALTERAR = "SEPARAÇÃO/DIVÓRCIO/PARTILHA - BENS TRIBUTÁVEIS ALTERAR";
	public static final String TELA_GIA_SEPARACAO_BEM_TRIBUTAVEL_IMOVEL_RURAL_ALTERAR = "SEPARAÇÃO/DIVÓRCIO/PARTILHA - IMÓVEL RURAL ALTERAR";
	public static final String TELA_GIA_SEPARACAO_BEM_TRIBUTAVEL_IMOVEL_URBANO_ALTERAR = "SEPARAÇÃO/DIVÓRCIO/PARTILHA - IMÓVEL URBANO ALTERAR";
	public static final String TELA_GIA_SEPARACAO_CONJUGE_ALTERAR = "SEPARAÇÃO/DIVÓRCIO/PARTILHA - CONJUGE ALTERAR";

	public static final int CODIGO_TELA_GIA_SEPARACAO_DADOS_GERAIS_ALTERAR = 59;
	public static final int CODIGO_TELA_GIA_SEPARACAO_BEM_TRIBUTAVEL_ALTERAR = 60;
	public static final int CODIGO_TELA_GIA_SEPARACAO_BEM_TRIBUTAVEL_IMOVEL_RURAL_ALTERAR = 61;
	public static final int CODIGO_TELA_GIA_SEPARACAO_BEM_TRIBUTAVEL_IMOVEL_URBANO_ALTERAR = 62;
	public static final int CODIGO_TELA_GIA_SEPARACAO_CONJUGE_ALTERAR = 63;
	 
	//GERAIS 
	public static final String TELA_GIA_SEPARACAO_DEMONSTRATIVO_CALCULO = "SEPARAÇÃO/DIVÓRCIO/PARTILHA - DEMONSTRATIVO DE CÁLCULO";
	public static final String TELA_GIA_SEPARACAO_DEMONSTRATIVO_CALCULO_CONSULTAR = "SEPARAÇÃO/DIVÓRCIO/PARTILHA - DEMONSTRATIVO DE CÁLCULO CONSULTAR";
	public static final String TELA_GIA_SEPARACAO_SENHA_CADASTRAR = "SEPARAÇÃO/DIVÓRCIO/PARTILHA - CADASTRAR SENHA";
	public static final String TELA_GIA_SEPARACAO_CONTRIBUINTE_SELECIONAR = "SEPARAÇÃO/DIVÓRCIO/PARTILHA - CONTRIBUINTE SELECIONAR";
	
	public static final int CODIGO_TELA_GIA_SEPARACAO_DEMONSTRATIVO_CALCULO = 64;
	public static final int CODIGO_TELA_GIA_SEPARACAO_DEMONSTRATIVO_CALCULO_CONSULTAR = 65;
	public static final int CODIGO_TELA_GIA_SEPARACAO_SENHA_CADASTRAR = 66;
	public static final int CODIGO_TELA_GIA_SEPARACAO_CONTRIBUINTE_SELECIONAR = 67;

	//GIA-ITCD CONSULTAR
	public static final String TELA_GIA_ITCD_CONSULTAR_LIVRE = "GIA-ITCD CONSULTA LIVRE";
	public static final String TELA_GIA_ITCD_CONSULTAR_SELECIONAR_CONTRIBUINTE = "GIA-ITCD CONSULTAR - SELECIONAR CONTRIBUINTE";
	public static final String TELA_GIA_ITCD_CONSULTAR_SERVIDOR = "GIA-ITCD CONSULTA SERVIDOR SEFAZ";

	public static final int CODIGO_TELA_GIA_ITCD_CONSULTAR_LIVRE = 68;
	public static final int CODIGO_TELA_GIA_ITCD_CONSULTAR_SELECIONAR_CONTRIBUINTE = 69;
	public static final int CODIGO_TELA_GIA_ITCD_CONSULTAR_SERVIDOR = 70;
	
	//GIA-ITCD REATIVAR
	public static final String TELA_GIA_ITCD_REATIVAR = "REATIVAR GIA - ITCD - DADOS DA GIA";
	
	public static final int CODIGO_TELA_GIA_ITCD_REATIVAR = 71;
	
	//GIA-ITCD INATIVAR
	public static final String TELA_GIA_ITCD_INATIVAR = "INATIVAR GIA - ITCD - DADOS DA GIA";
	
	public static final int CODIGO_TELA_GIA_ITCD_INATIVAR = 72;
	
	//REIMPRIMIR
	//NOTIFICAÇÃO / RETIFICAÇÃO
	public static final String TELA_GIA_ITCD_REIMPRIMIR_NOTIFICACAO_RETIFICACAO = "REIMPRESSÃO DA NOTIFICAÇÃO/RETIFICAÇÃO";
	public static final String TELA_GIA_ITCD_CONSULTAR_NOTIFICACAO_RETIFICACAO = "FILTRO PESQUISA - REIMPRESSÃO DA NOTIFICAÇÃO/RETIFICAÇÃO";
	public static final String TELA_GIA_ITCD_REIMPRIMIR = "REIMPRIMIR GIA - ITCD";
	public static final String TELA_GIA_ITCD_CONSULTAR_REIMPRIMIR = "FILTRO PESQUISA - REIMPRIMIR GIA - ITCD";	
	
	public static final int CODIGO_TELA_GIA_ITCD_REIMPRIMIR_NOTIFICACAO_RETIFICACAO = 73;
	public static final int CODIGO_TELA_GIA_ITCD_REIMPRIMIR = 74;
	public static final int CODIGO_TELA_GIA_ITCD_CONSULTAR_NOTIFICACAO_RETIFICACAO = 90;
	public static final int CODIGO_TELA_GIA_ITCD_CONSULTAR_REIMPRIMIR = 91;
		
	//AUTENTICIDADE
	public static final String TELA_GIA_ITCD_CONSULTAR_AUTENTICIDADE = "FILTRO PARA CONSULTAR AUTENTICIDADE - FILTRO PARA PESQUISA";
	public static final String TELA_GIA_ITCD_CONSULTAR_AUTENTICIDADE_IMPRIMIR_AUTENTICIDADE = "IMPRIMIR AUTENTICIDADE  - DADOS DA GIA - ITCD";
	
	public static final int CODIGO_TELA_GIA_ITCD_CONSULTAR_AUTENTICIDADE = 75;
	public static final int CODIGO_TELA_GIA_ITCD_CONSULTAR_AUTENTICIDADE_IMPRIMIR_AUTENTICIDADE = 76;
		
	//ALTERAR STATUS
	public static final String TELA_GIA_ITCD_STATUS_ALTERAR = "ALTERAR STATUS - DADOS DA GIA - ITCD";
	
	public static final int CODIGO_TELA_GIA_ITCD_STATUS_ALTERAR = 77;
	
	//AVALIACAO
	//INCLUIR
	public static final String TELA_GIA_ITCD_AVALIACAO_INCLUIR = "INCLUIR AVALIAÇÃO - DADOS DA GIA";
	public static final String TELA_GIA_ITCD_AVALIACAO_INCLUIR_AVALIACAO_BEM = "INCLUIR AVALIAÇÃO - DADOS DA AVALIAÇÃO DO BEM";
	public static final String TELA_GIA_ITCD_AVALIACAO_INCLUIR_AVALIACAO_BEM_SERVIDOR_INCLUIR = "INCLUIR AVALIAÇÃO - AVALIADOR SELECIONAR";
	
	public static final int CODIGO_TELA_GIA_ITCD_AVALIACAO_INCLUIR = 78;
	public static final int CODIGO_TELA_GIA_ITCD_AVALIACAO_INCLUIR_AVALIACAO_BEM = 79;
	public static final int CODIGO_TELA_GIA_ITCD_AVALIACAO_INCLUIR_AVALIACAO_BEM_SERVIDOR_INCLUIR = 80;
	
	//ALTERAR
	public static final String TELA_GIA_ITCD_AVALIACAO_ALTERAR = "ALTERAR AVALIAÇÃO - DADOS DA GIA";
	public static final String TELA_GIA_ITCD_AVALIACAO_ALTERAR_AVALIACAO_BEM = "ALTERAR AVALIAÇÃO - DADOS DA AVALIAÇÃO DO BEM";
	public static final String TELA_GIA_ITCD_AVALIACAO_ALTERAR_AVALIACAO_BEM_SERVIDOR_INCLUIR = "ALTERAR AVALIAÇÃO - AVALIADOR SELECIONAR";
	
	public static final int CODIGO_TELA_GIA_ITCD_AVALIACAO_ALTERAR = 81;
	public static final int CODIGO_TELA_GIA_ITCD_AVALIACAO_ALTERAR_AVALIACAO_BEM = 82;
	public static final int CODIGO_TELA_GIA_ITCD_AVALIACAO_ALTERAR_AVALIACAO_BEM_SERVIDOR_INCLUIR = 83;
	
	//CONSULTAR
	public static final String TELA_GIA_ITCD_AVALIACAO_CONSULTAR = "FILTRO PESQUISA - AVALIAÇÃO CONSULTAR";
	
	public static final int CODIGO_TELA_GIA_ITCD_AVALIACAO_CONSULTAR = 84;
	
	//IMPRIMIR
	public static final String TELA_GIA_ITCD_AVALIACAO_IMPRIMIR = "IMPRIMIR AVALIAÇÃO - DADOS DA GIA";
	
	public static final int CODIGO_TELA_GIA_ITCD_AVALIACAO_IMPRIMIR = 86;
	
	//VINCULAR DAR
	public static final String TELA_GIA_ITCD_VINCULAR_DAR = "VINCULAR DAR A GIA-ITCD - DADOS DA GIA-ITCD";
	
	public static final int CODIGO_TELA_GIA_ITCD_VINCULAR_DAR = 87;
	
	
	//ENVIAR SENHA
	public static final String TELA_GIA_ITCD_SENHA_ENVIAR = "ENVIAR SENHA GIA - ITCD - FILTRO PARA PESQUISA";
	
	public static final int CODIGO_TELA_GIA_ITCD_SENHA_ENVIAR = 88;
		
	//MULTA MORA INCLUIR
	public static final String TELA_MULTA_MORA_INCLUIR = "DADOS DO REGISTRO - MULTA DE MORA INCLUIR";

	public static final int CODIGO_TELA_MULTA_MORA_INCLUIR = 89;
	
	
	
	
	
}
