package br.gov.mt.sefaz.itc.model.tabelabasica.ajuda.cargainicial;

public interface TelaFuncionalidade
{
	public static final String TELA_FUNCIONALIDADE_ABA_BENS_TRIBUTAVEIS = "TELA RESPONSÁVEL POR INCLUIR BENS TRIBUTÁVEIS PARA A GIA-ITCD.O PROCEDIMENTO DE USO TEM\\n\" + \n" + 
	"	   \"O SEGUINTE FLUXO:\\n\" + \n" + 
	"	   \"1- DEFINA A CLASSIFICAÇÃO DO BEM.\\n\" + \n" + 
	"	   \"2- DEFINA O TIPO DO BEM.\\n\" + \n" + 
	"	   \"3- INSIRA A DESCRIÇÃO DO BEM.\\n\" + \n" + 
	"	   \"4- CASO O TIPO DO BEM SEJA OUTROS BENS INSIRA O VALOR DE MERCADO .\\n\" + \n" + 
	"	   \"5- MARQUE O CAMPO ISENÇÃO PREVISTA EM LEI CASO NECESSÁRIO.\\n\" + \n" + 
	"	   \"6- EXECUTE A OPERAÇÃO ADICIONAR PARA ADICIONAR O BEM.\\n\" + \n" + 
	"	   \"OBS: É POSSÍVEL ADICIONAR MAIS DE UM BEM.\\n\" + \n" + 
	"	   \"7- EXECUTE A OPERAÇÃO SALVAR.\\n\" + \n" + 
	"	   \"OBS: CASO DESEJE ALTERAR O BEM INSERIDO CLIQUE NO LINK ALTERAR.\\n\" + \n" + 
	"	   \"OBS: CASO DESEJE EXCLUIR O BEM INSERIDO CLIQUE NO LINK EXCLUIR.";
	
	public static final String TELA_FUNCIONALIDADE_ABA_BENS_TRIBUTAVEIS_FICHA_IMOVEL_RURAL = "TELA RESPONSÁVEL POR INSERIR OS DADOS DO IMÓVEL RURAL.O PROCEDIMENTO DE USO TEM O \\n\" + \n" + 
	"	   \"SEGUINTE FLUXO:\\n\" + \n" + 
	"	   \"1- INSIRA A DENOMINAÇÃO DO IMÓVEL.\\n\" + \n" + 
	"	   \"2- DEFINA O TIPO LOGRADOURO.\\n\" + \n" + 
	"	   \"3- INSIRA O LOGRADOURO.\\n\" + \n" + 
	"	   \"4- INSIRA O NÚMERO.\\n\" + \n" + 
	"	   \"5- INSIRA O COMPLEMENTO.\\n\" + \n" + 
	"	   \"6- INSIRA O PONTO DE REFERENCIA.\\n\" + \n" + 
	"	   \"7- INSIRA CEP E EXECUTE A OPERAÇÃO PESQUISAR.\\n\" + \n" + 
	"	   \"8- DEFINA AS DIVISAS.\\n\" + \n" + 
	"	   \"9- INSIRA O KM DO PERÍMETRO URBANO.\\n\" + \n" + 
	"	   \"10- INSIRA A ÁREA TOTAL DO IMÓVEL.\\n\" + \n" + 
	"	   \"11- INSIRA O NÚMERO INDEA/MT.\\n\" + \n" + 
	"	   \"12- INSIRA O CÓDIGO NA RECEITA FEDERAL.\\n\" + \n" + 
	"	   \"13- DEFINA SE POSSUI PASTAGENS NATURAIS E/OU CULTIVADAS.\\n\" + \n" + 
	"	   \"14- INSIRA O TAMANHO DAS PASTAGENS SE NECESSÁRIO.\\n\" + \n" + 
	"	   \"15- INSIRA O VALOR DAS PASTAGENS SE NECESSÁRIO.\\n\" + \n" + 
	"	   \"16- DEFINA SE POSSUI JAZIDAS MINERAIS, FONTES DE ÁGUA RADIOATIVA, TÉRMICAS E/OU \\n\" + \n" + 
	"	   \"MINERAIS.\\n\" + \n" + 
	"	   \"17- INSIRA O VALOR DAS ACESSÕES NATURAIS.\\n\" + \n" + 
	"	   \"18- INSIRA O VALOR IMÓVEL.\\n\" + \n" + 
	"	   \"19- INSIRA O VALOR MÁQUINAS E IMPLEMENTOS AGRÍCOLAS.\\n\" + \n" + 
	"	   \"20- INSIRA OUTROS VALORES.\\n\" + \n" + 
	"	   \"21- INSIRA O VALOR VENAL DO ITR.\\n\" + \n" + 
	"	   \"22- EXECUTE A OPERAÇÃO ADICIONAR.\\n\" + \n" + 
	"	   \"OBS: OS SEGUINTES CAMPOS NÃO SÃO OBRIGATÓRIOS: TIPO LOGRADOURO, NÚMERO, COMPLEMENTO, \\n\" + \n" + 
	"	   \"DIVISAS, NÚMERO INDEA/MT, CÓDIGO NA RECEITA FEDERAL, VALOR DE MERCADO DAS MÁQUINAS E \\n\" + \n" + 
	"	   \"IMPLEMENTOS AGRÍCOLAS, OUTROS VALORES.";
	
	public static final String TELA_FUNCIONALIDADE_ABA_BENS_TRIBUTAVEIS_FICHA_IMOVEL_URBANO = "TELA RESPONSÁVEL POR RECEBER OS DADOS DO IMÓVEL URBANO.O PROCEDIMENTO DE USO TEM O \\n\" + \n" + 
	"	   \"SEGUINTE FLUXO:\\n\" + \n" + 
	"	   \"1- DEFINA O TIPO DE LOGRADOURO.\\n\" + \n" + 
	"	   \"2- INSIRA O LOGRADOURO.\\n\" + \n" + 
	"	   \"3- INSIRA O NÚMERO.\\n\" + \n" + 
	"	   \"4- INSIRA O BAIRRO.\\n\" + \n" + 
	"	   \"5- INSIRA O PONTO DE REFERENCIA.\\n\" + \n" + 
	"	   \"6- INSIRA O COMPLEMENTO.\\n\" + \n" + 
	"	   \"7- INSIRA O CEP E EXECUTE A OPERAÇÃO PESQUISAR.\\n\" + \n" + 
	"	   \"8- DEFINA O ESTADO DE CONSERVAÇÃO.\\n\" + \n" + 
	"	   \"9- INSIRA A ÁREA TOTAL DO IMÓVEL.\\n\" + \n" + 
	"	   \"10- INSIRA A ÁREA CONSTRUÍDA.\\n\" + \n" + 
	"	   \"11- DEFINA O TIPO DE CONSTRUÇÃO.\\n\" + \n" + 
	"	   \"12- DEFINA O TIPO DE ACESSO.\\n\" + \n" + 
	"	   \"13- DEFINA A BENFEITORIA E EXECUTE A OPERAÇÃO ADICIONAR.\\n\" + \n" + 
	"	   \"14- INSIRA O VALOR TOTAL DE MERCADO.\\n\" + \n" + 
	"	   \"15- INSIRA O VALOR VENAL.\\n\" + \n" + 
	"	   \"16- EXECUTE A OPERAÇÃO ADICIONAR.\\n\" + \n" + 
	"	   \"OBS: É POSSÍVEL ADICIONAR MAIS DE UMA BENFEITORIA.\\n\" + \n" + 
	"	   \"OBS: OS CAMPOS COMPLEMENTO, PONTO DE REFERENCIA E BENFEITORIA NÃO SÃO OBRIGATÓRIOS.";
	
	public static final String TELA_FUNCIONALIDADE_CONSULTAR_GIA_ITCD_GERAL_CONTRIBUINTE = "TELA RESPONSÁVEL POR LOCALIZAR UMA GIA-ITCD PARA SER ALTERADA .O PROCEDIMENTO DE USO \\n\" + \n" + 
	"		\"TEM O SEGUINTE FLUXO:\\n\" + \n" + 
	"		\"1- LOCALIZE O CONTRIBUINTE.\\n\" + \n" + 
	"		\"2- INSIRA O NÚMERO DA GIA-ITCD.\\n\" + \n" + 
	"		\"3- INSIRA A SENHA REFERENTE A GIA-ITCD.\\n\" + \n" + 
	"		\"4- EXECUTE A OPERAÇÃO PESQUISAR.\\n\" + \n" + 
	"		\"OBS: CASO NÃO LEMBRE A SENHA DA GIA-ITCD CLIQUE NO LINK ESQUECI MINHA SENHA.";

	public static final String TELA_FUNCIONALIDADE_CONSULTAR_GIA_ITCD_GERAL_SERVIDOR = "TELA RESPONSÁVEL POR LOCALIZAR UMA GIA-ITCD PARA SER ALTERADA .O PROCEDIMENTO DE USO \\n\" + \n" + 
	"		\"TEM O SEGUINTE FLUXO:\\n\" + \n" + 
	"		\"1- LOCALIZE O CONTRIBUINTE.\\n\" + \n" + 
	"		\"2- INSIRA O NÚMERO DA GIA-ITCD.\\n\" + \n" + 
	"		\"3- INSIRA A SENHA REFERENTE A GIA-ITCD.\\n\" + \n" + 
	"		\"4- EXECUTE A OPERAÇÃO PESQUISAR.\\n\" + \n" + 
	"		\"OBS: CASO NÃO LEMBRE A SENHA DA GIA-ITCD CLIQUE NO LINK ESQUECI MINHA SENHA.";
	
	public static final String TELA_FUNCIONALIDADE_ABA_DEMONSTRATIVO_CALCULO = "TELA RESPONSÁVEL POR APRESENTAR UM CÁLCULO DEMONSTRATIVO A PARTIR DOS DADOS INSERIDOS \\n\" + \n" + 
	"	   \"NA GIA-ITCD .O PROCEDIMENTO DE USO TEM O SEGUINTE FLUXO:\\n\" + \n" + 
	"	   \"1- APOS VERIFICAR OS DADOS EXECUTE A OPERAÇÃO CONFIRMAR.\\n\" + \n" + 
	"	   \"OBS: OS VALORES APRESENTADOS SÃO CALCULADOS DE ACORDO COM OS DADOS DECLARADOS PELO \\n\" + \n" + 
	"	   \"CONTRIBUINTE E PODERÃO SOFRER ALTERAÇÕES DEPOIS DE PASSAREM PELA AVALIAÇÃO DA \\n\" + \n" + 
	"	   \"SECRETARIA DA FAZENDA.\\n\" + \n" + 
	"	   \"OBS: CASO O STATUS DA GIA-ITCD SEJA RETIFICADA OU NOTIFICADA É POSSÍVEL GERAR O DAR \\n\" + \n" + 
	"	   \"EXECUTANDO A OPERAÇÃO GERAR DAR.";	
	
	
}
