package br.gov.mt.sefaz.itc.util.facade;

import br.gov.mt.sefaz.itc.util.dominio.DomnGrupoPermissao;


public interface ConfiguracaoITCD
{
   public static final String SIGLA_ESTADO_MATO_GROSSO = "MT";
   public static final int CODIGO_CEP_CAPITAL_MATO_GROSSO = 78000000;
   public static final String SIGLA_GERENCIA_GIOR = "GIOR";
   public static final String SIGLA_SUPERINTENDENCIA_SUED = "SUED";
   public static final String SIGLA_GERENCIA_NORTE = "GSNO";
   public static final String SIGLA_GERENCIA_SUL = "GSSU";
   public static final String SIGLA_GERENCIA_LESTE = "GSLE";
   public static final String SIGLA_GERENCIA_OESTE = "GSOE";
   public static final String NOME_SUPERINTENDENCIA = 
      "SUPERINTENDÊNCIA DE ATENDIMENTO AO CONTRIBUINTE – SAC";
   public static final String NOME_GERENCIA = 
      "COORDENADORIA DO ITCD E OUTRAS RECEITAS – CITCD";

   public static final String DECLARANTE = "declarante";
   public static final String PROCURADOR = "procurador";

   public static final int CODIGO_TIPO_UNIDADE_SEFAZ_AGENFA = 1;
   public static final int CODIGO_TIPO_UNIDADE_SEFAZ_GERENCIA = 4;

   public static final int PRAZO_MAXIMO_GIA_ITCD_PARCELADA = 60;

   public static final int CODIGO_LOCAL_EMISSAO_DAR = 6;

   public static final int PRAZO_VENCIMENTO_DAR = 29;

   public static final int CODIGO_TRIBUTO_ARRECADACAO = 7110;
   public static final int CODIGO_TRIBUTO_ARRECADACAO_PARCELAMENTO = 7129;
   public static final int CODIGO_TRIBUTO_LANCAMENTO_OFICIO_PARCELAMENTO = 
      7112;

   public static final int TAMANHO_MAXIMO_DESCRICAO_COMPLEMENTAR_BENFEITORIA = 
      50;

   public static final boolean NAO_GERA_LOG = false;

   //PARAMETROS UTILIZADOS EM TESTE
   public static final int PERMISSAO = 
      DomnGrupoPermissao.CODG_GRUPO_PERM_ITCDCONSULTA;

   //CONFIGURACAO GERENCIAL DE PARAMETROS	
   public static final String PARAMETRO_AREA_MINIMA_HECTARES_IMOVEL_RURAL = 
      "ÁREA MÍNIMA EM HECTARES DO IMÓVEL RURAL";
   public static final String PARAMETRO_BASE_CALCULO_IMPOSTO = 
      "BASE DE CÁLCULO DE IMPOSTO";
   public static final String PARAMETRO_DISTANCIA_KM_PERIMETRO_URBANO = 
      "DISTÂNCIA EM KM DO PERÍMETRO URBANO";
   public static final String PARAMETRO_INFORMACOES_PROTOCOLO_GIA_ITCD = 
      "INFORMAÇÕES DO PROTOCOLO GIA-ITCD";
   public static final String PARAMETRO_INFORMACOES_PROTOCOLO_AUTOMATICO_GIA_ITCD = 
      "INFORMAÇÕES DO PROTOCOLO GIA-ITCD AUTOMÁTICO";
   public static final String PARAMETRO_LIMITE_MINIMO_AREA_CONSTRUIDA_IMOVEL_URBANO = 
      "LIMITE MÍNINO DA ÁREA CONSTRUÍDA DO IMÓVEL URBANO";
   public static final String PARAMETRO_LISTA_DOCUMENTOS_GIA_INVENTARIO_ARROLAMENTO = 
      "LISTA DE DOCUMENTOS NECESSÁRIOS PARA GIA-ITCD - INVENTÁRIO/ARROLAMENTO";
   public static final String PARAMETRO_LISTA_DOCUMENTOS_GIA_SEPARACAO = 
      "LISTA DE DOCUMENTOS NECESSÁRIOS PARA GIA-ITCD - SEPARAÇÃO/DIVÓRCIO/PARTILHA";
   public static final String PARAMETRO_LISTA_DOCUMENTOS_GIA_DOACAO = 
      "LISTA DOCUMENTOS NECESSÁRIOS PARA GIA-ITCD - DOAÇÃO";
   public static final String PARAMETRO_PRAZO_ABERTURA_PROCESSO_INVENTARIO = 
      "PRAZO DE ABERTURA DO PROCESSO DE INVENTÁRIO";
   public static final String PARAMETRO_PRAZO_IMPUGNACAO = 
      "PRAZO DE IMPUGNAÇÃO";
   public static final String PARAMETRO_PRAZO_VENCIMENTO_DAR = 
      "PRAZO DE VENCIMENTO DO DAR";
   public static final String PARAMETRO_CODIGO_DE_AGENFA_DE_PROTOCOLO_E_AVALIACAO_AUTOMATICA = 
      "CÓDIGO DE AGENFA DE PROTOCOLO E AVALIAÇÃO AUTOMÁTICA";
   public static final String PARAMETRO_PRAZO_VENCIMENTO_PROTOCOLO_GIA_REATIVADA = 
      "PRAZO DE VENCIMENTO PARA PROTOCOLO DA GIA REATIVADA";
   public static final String PARAMETRO_PRAZO_AVALIACAO_JUDICIAL = 
      "PRAZO PARA AVALIAÇÃO JUDICIAL";
   public static final String PARAMETRO_PRAZO_VENCIMENTO_PROTOCOLAR_GIA = 
      "PRAZO VENCIMENTO PARA PROTOCOLAR GIA-ITCD";
   public static final String PARAMETRO_TEXTO_DESCRITIVO_REFERENTE_BENEFICIARIO = 
      "TEXTO DESCRITIVO (CONTRIBUINTE) REFERENTE A BENEFICIARIO";
   public static final String PARAMETRO_TEXTO_DESCRITIVO_BENS_DIREITOS = 
      "TEXTO DESCRITIVO (CONTRIBUINTE) REFERENTE A BENS DE DIREITOS";
   public static final String PARAMETRO_TEXTO_DESCRITIVO_DECLARACAO_NAO_OCORRENCIA_FATO_GERADOR = 
      "TEXTO DESCRITIVO DA DECLARAÇÃO DE NÃO OCORRÊNCIA DO FATO GERADOR, TIPO \"INTER VIVOS\"- \"SEPARAÇÕES/DIVÓRCIO/PARTILHA\" \"DECLARAÇÃO DE NÃO OCORRÊNCIA DO FATO GERADOR\"";
   public static final String PARAMETRO_TEXTO_DESCRITIVO_DECLARACAO_ISENCAO_VALORES = 
      "TEXTO DESCRITIVO DA DECLARAÇÃO \"ISENÇÃO POR VALORES\"";
   public static final String PARAMETRO_TEXTO_DESCRITIVO_DECLARACAO_DISPENSA_RECOLHIMENTO = 
      "TEXTO DESCRITIVO DA DECLARAÇÃO \"DISPENSA DE RECOLHIMENTO POR VALOR ITCD INFERIOR A 1 UPF\"";
   public static final String PARAMETRO_TEXTO_DESCRITIVO_DECLARACAO_ISENCAO_VALORES_GIA_INVENTARIO = 
      "TEXTO DESCRITIVO DA DECLARAÇÃO TIPO \"CAUSA MORTIS\" - \"INVENTÁRIO\" OU \"ARROLAMENTO\" (ISENÇÃO POR VALOR DE UPF)";
   public static final String PARAMETRO_TEXTO_DESCRITIVO_DECLARACAO_ISENCAO_VALORES_GIA_DOACAO = 
      "TEXTO DESCRITIVO DA DECLARAÇÃO TIPO \"INTER VIVOS\" - \"DOAÇÕES SIMPLES\" (ISENÇÃO POR VALOR DE UPF)";
   public static final String PARAMETRO_TEXTO_DESCRITIVO_DECLARACAO_ISENCAO_VALORES_GIA_SEPARACAO = 
      "TEXTO DESCRITIVO DA DECLARAÇÃO, TIPO \"INTER VIVOS\" - SEPARAÇÕES/DIVÓRCIO/PARTILHA (ISENÇÃO POR VALOR DE UPF)";
   public static final String PARAMETRO_TEXTO_DESCRITIVO_GIA_RETIFICADORA = 
      "TEXTO DESCRITIVO DA GIA-ITCD RETIFICADORA";
   public static final String PARAMETRO_TEXTO_DESCRITIVO_GIA_INVENTARIO = 
      "TEXTO DESCRITIVO DA GIA-ITCD TIPO \"CAUSA MORTIS\" - \"INVENTÁRIO\" OU \"ARROLAMENTO\"";
   public static final String PARAMETRO_TEXTO_DESCRITIVO_GIA_DOACAO = 
      "TEXTO DESCRITIVO DA GIA-ITCD TIPO \"INTER VIVOS\" - \"DOAÇÕES SIMPLES\"";
   public static final String PARAMETRO_TEXTO_DESCRITIVO_GIA_SEPARACAO = 
      "TEXTO DESCRITIVO DA GIA-ITCD TIPO \"INTER VIVOS\" - \"SEPARAÇÕES/DIVÓRCIO/PARTILHA\"";
   public static final String PARAMETRO_TEXTO_DESCRITIVO_DEMONSTRATIVO_CALCULO = 
      "TEXTO DESCRITIVO DO DEMONSTRATIVO DE CÁLCULO";
   public static final String PARAMETRO_TEXTO_DESCRITIVO_NOTIFICACAO = 
      "TEXTO DESCRITO (CONTRIBUINTE) DA NOTIFICAÇÃO";
   public static final String PARAMETRO_TEXTO_INFORMATIVO_NOTIFICACAO = 
      "TEXTO DESCRITO (INFORMAÇÃO) DA NOTIFICAÇÃO";
   public static final String PARAMETRO_VALOR_TOTAL_BENS = 
      "VALOR TOTAL DE BENS";
   public static final String PARAMETRO_CODIGO_UNIDADE_FAZENDARIA = 
      "CODIGO UNIDADE FAZENDARIA";

   public static final String MENSAGEM_JUSTIFICATIVA_INSCRICAO_DIVIDA_ATIVA_AUTOMATICAMENTE = 
      "GIA-ITCD Vencida. Status alterado para Inscrição em Dívida Ativa automaticamente.";

   /*DADOS GERACAO LOG*/
   public static final String BROWSER = "IE";
   public static final String HOST_NAME = "ITCD";
   public static final String ENDERECO_IP = "127.0.0.1";
   public static final String MAC = "MAC-SEFAZ";
   public static final String NOME_OS = "WINDOWS";
   public static final int CODIGO_USUARIO = 999999997;
   public static final String NOME_USUARIO = "PROCESSAMENTO BATCH DE SISTEMA";
   public static final String IDENTIFICACAO = "" + CODIGO_USUARIO;
   public static final String CODIGO_MODULO = "MODABERTO";

   //PARAMETROS DO INSTRUMENTO CONSTITUTIVO DO CCF
   public static final String SIGLA_INSTRUMENTO_CONSTITUTIVO_ITCD = "GIA ITCD";

   //Sistema
   public static final String SIGLA_ITC = "ITC";

   public static final String QUANTIDADE_DE_PARCELAS_POR_COTA = 
      "QUANTIDADE DE PARCELAS POR COTA";

   public static final String SIGLA_SISTEMA_ITCD = "ITCD";
   public static final String CONFIGURACAO_NOTIFICACAO_SNE = 
      "CONFIGURAÇÃO NOTIFICAÇÃO SNE";
}
