package br.gov.mt.sefaz.itc.model.tabelabasica.ajuda.cargainicial;

public interface FuncionalidadeAjuda
{
	//TABELAS BÁSICAS
	
	//BENS
	public static final String FUNCIONALIDADE_BENS_INCLUIR = "INCLUIR BENS";
	public static final String FUNCIONALIDADE_BENS_ALTERAR = "ALTERAR BENS";
	public static final String FUNCIONALIDADE_BENS_CONSULTAR = "CONSULTAR BENS";
	
	public static final int CODIGO_FUNCIONALIDADE_BENS_INCLUIR = 1;
	public static final int CODIGO_FUNCIONALIDADE_BENS_ALTERAR = 2;
	public static final int CODIGO_FUNCIONALIDADE_BENS_CONSULTAR = 3;
	
	//CONSTRUCAO
	public static final String FUNCIONALIDADE_CONSTRUCAO_INCLUIR = "INCLUIR CONSTRUÇÃO";
	public static final String FUNCIONALIDADE_CONSTRUCAO_ALTERAR = "ALTERAR CONSTRUÇÃO";
	public static final String FUNCIONALIDADE_CONSTRUCAO_CONSULTAR = "CONSULTAR CONSTRUÇÃO";
	
	public static final int CODIGO_FUNCIONALIDADE_CONSTRUCAO_INCLUIR = 4;
	public static final int CODIGO_FUNCIONALIDADE_CONSTRUCAO_ALTERAR = 5;
	public static final int CODIGO_FUNCIONALIDADE_CONSTRUCAO_CONSULTAR = 6;
	
	//CULTURA
	public static final String FUNCIONALIDADE_CULTURA_INCLUIR = "INCLUIR CULTURA";
	public static final String FUNCIONALIDADE_CULTURA_ALTERAR = "ALTERAR CULTURA";
	public static final String FUNCIONALIDADE_CULTURA_CONSULTAR = "CONSULTAR CULTURA";
	
	public static final int CODIGO_FUNCIONALIDADE_CULTURA_INCLUIR = 7;
	public static final int CODIGO_FUNCIONALIDADE_CULTURA_ALTERAR = 8;
	public static final int CODIGO_FUNCIONALIDADE_CULTURA_CONSULTAR = 9;
	
	//INCLUIR MULTA DE MORA
	public static final String FUNCIONALIDADE_INCLUIR_MULTA_MORA_INCLUIR = "INCLUIR MULTA DE MORA";
	
	public static final int CODIGO_FUNCIONALIDADE_INCLUIR_MULTA_MORA_INCLUIR = 10;
	
	//REBANHO
	public static final String FUNCIONALIDADE_REBANHO_INCLUIR = "INCLUIR REBANHO";
	public static final String FUNCIONALIDADE_REBANHO_ALTERAR = "ALTERAR REBANHO";
	public static final String FUNCIONALIDADE_REBANHO_CONSULTAR = "CONSULTAR REBANHO";
	
	public static final int CODIGO_FUNCIONALIDADE_REBANHO_INCLUIR = 11;
	public static final int CODIGO_FUNCIONALIDADE_REBANHO_ALTERAR = 12;
	public static final int CODIGO_FUNCIONALIDADE_REBANHO_CONSULTAR = 13;
	
	//PARÂMETROS DE LEGISLAÇÃO
	public static final String FUNCIONALIDADE_PARAMETROS_LEGISLACAO_INCLUIR = "INCLUIR PARÂMETROS DE LEGISLAÇÃO";
	public static final String FUNCIONALIDADE_PARAMETROS_LEGISLACAO_ALTERAR = "ALTERAR PARÂMETROS DE LEGISLAÇÃO";
	public static final String FUNCIONALIDADE_PARAMETROS_LEGISLACAO_CONSULTAR = "CONSULTAR PARÂMETROS DE LEGISLAÇÃO";
	
	public static final int CODIGO_FUNCIONALIDADE_PARAMETROS_LEGISLACAO_INCLUIR = 14;
	public static final int CODIGO_FUNCIONALIDADE_PARAMETROS_LEGISLACAO_ALTERAR = 15;
	public static final int CODIGO_FUNCIONALIDADE_PARAMETROS_LEGISLACAO_CONSULTAR = 16;
	
	//NATUREZA DA OPERAÇÃO
	public static final String FUNCIONALIDADE_NATUREZA_OPERACAO_INCLUIR = "INCLUIR NATUREZA DA OPERAÇÃO";
	public static final String FUNCIONALIDADE_NATUREZA_OPERACAO_ALTERAR = "ALTERAR NATUREZA DA OPERAÇÃO";
	public static final String FUNCIONALIDADE_NATUREZA_OPERACAO_CONSULTAR = "CONSULTAR NATUREZA DA OPERAÇÃO";
	
	public static final int CODIGO_FUNCIONALIDADE_NATUREZA_OPERACAO_INCLUIR = 17;
	public static final int CODIGO_FUNCIONALIDADE_NATUREZA_OPERACAO_ALTERAR = 18;
	public static final int CODIGO_FUNCIONALIDADE_NATUREZA_OPERACAO_CONSULTAR = 19;
	
	//AJUDA
	public static final String FUNCIONALIDADE_AJUDA_INCLUIR = "INCLUIR AJUDA";
	public static final String FUNCIONALIDADE_AJUDA_ALTERAR = "ALTERAR AJUDA";
	public static final String FUNCIONALIDADE_AJUDA_CONSULTAR = "CONSULTAR AJUDA";
	
	public static final int CODIGO_FUNCIONALIDADE_AJUDA_INCLUIR = 20;
	public static final int CODIGO_FUNCIONALIDADE_AJUDA_ALTERAR = 21;
	public static final int CODIGO_FUNCIONALIDADE_AJUDA_CONSULTAR = 22;
	
	//CONFIGURACAO_GERENCIAL_PARAMETROS
	public static final String FUNCIONALIDADE_CONFIGURACAO_GERENCIAL_PARAMETROS_ALTERAR = "ALTERAR CONFIGURAÇÃO GERENCIAL DE PARÂMETROS";
	
	public static final int CODIGO_FUNCIONALIDADE_CONFIGURACAO_GERENCIAL_PARAMETROS_ALTERAR = 23;
	
	//BENFEITORIAS
	public static final String FUNCIONALIDADE_BENFEITORIAS_INCLUIR = "INCLUIR BENFEITORIAS";
	public static final String FUNCIONALIDADE_BENFEITORIAS_ALTERAR = "ALTERAR BENFEITORIAS";
	public static final String FUNCIONALIDADE_BENFEITORIAS_CONSULTAR = "CONSULTAR BENFEITORIAS";
	
	public static final int CODIGO_FUNCIONALIDADE_BENFEITORIAS_INCLUIR = 24;
	public static final int CODIGO_FUNCIONALIDADE_BENFEITORIAS_ALTERAR = 25;
	public static final int CODIGO_FUNCIONALIDADE_BENFEITORIAS_CONSULTAR = 26;
	
	
	//GIA-ITCD	
	//AUTENTICIDADE
	public static final String FUNCIONALIDADE_AUTENTICIDADE_IMPRIMIR = "IMPRIMIR AUTENTICIDADE";
	public static final String FUNCIONALIDADE_AUTENTICIDADE_CONSULTAR = "CONSULTAR AUTENTICIDADE";
	
	public static final int CODIGO_FUNCIONALIDADE_AUTENTICIDADE_IMPRIMIR = 27;
	public static final int CODIGO_FUNCIONALIDADE_AUTENTICIDADE_CONSULTAR = 28;
	
	//AVALIAÇÃO
	public static final String FUNCIONALIDADE_AVALIACAO_INCLUIR = "INCLUIR AVALIAÇÃO";
	public static final String FUNCIONALIDADE_AVALIACAO_ALTERAR = "ALTERAR AVALIAÇÃO";
	public static final String FUNCIONALIDADE_AVALIACAO_CONSULTAR = "CONSULTAR AVALIAÇÃO";
	public static final String FUNCIONALIDADE_AVALIACAO_IMPRIMIR = "IMPRIMIR AVALIAÇÃO";
	
	public static final int CODIGO_FUNCIONALIDADE_AVALIACAO_INCLUIR = 29;
	public static final int CODIGO_FUNCIONALIDADE_AVALIACAO_ALTERAR = 30;
	public static final int CODIGO_FUNCIONALIDADE_AVALIACAO_CONSULTAR = 31;
	public static final int CODIGO_FUNCIONALIDADE_AVALIACAO_IMPRIMIR = 32;
	
	//ALTERAR STATUS
	public static final String FUNCIONALIDADE_STATUS_ALTERAR = "ALTERAR STATUS GIA - ITCD";
	
	public static final int CODIGO_FUNCIONALIDADE_STATUS_ALTERAR = 33;
	
	//REIMPRIMIR
	public static final String FUNCIONALIDADE_REIMPRIMIR_GIA_ITCD = "REIMPRIMIR GIA - ITCD";
	public static final String FUNCIONALIDADE_REIMPRIMIR_NOTIFICACAO_RETIFICACAO = "REIMPRESSÃO DA NOTIFICAÇÃO/RETIFICAÇÃO";
	
	public static final int CODIGO_FUNCIONALIDADE_REIMPRIMIR_GIA_ITCD = 34;
	public static final int CODIGO_FUNCIONALIDADE_REIMPRIMIR_NOTIFICACAO_RETIFICACAO = 35;
	
	//CAUSA MORTIS
	public static final String FUNCIONALIDADE_GIA_INVENTARIO_ARROLAMENTO_INCLUIR = "INCLUIR GIA - ITCD INVENTÁRIO ARROLAMENTO";
	public static final String FUNCIONALIDADE_GIA_INVENTARIO_ARROLAMENTO_ALTERAR = "ALTERAR GIA - ITCD INVENTÁRIO ARROLAMENTO";
	
	public static final int CODIGO_FUNCIONALIDADE_GIA_INVENTARIO_ARROLAMENTO_INCLUIR = 36;
	public static final int CODIGO_FUNCIONALIDADE_GIA_INVENTARIO_ARROLAMENTO_ALTERAR = 37;
	
	//INTER VIVOS	
	public static final String FUNCIONALIDADE_GIA_DOACAO_INCLUIR = "INCLUIR GIA - ITCD DOAÇÃO / OUTROS";
	public static final String FUNCIONALIDADE_GIA_DOACAO_ALTERAR = "ALTERAR GIA - ITCD DOAÇÃO / OUTROS";
	public static final String FUNCIONALIDADE_GIA_SEPARACAO_INCLUIR = "INCLUIR GIA - ITCD SEPARAÇÃO/DIVÓRCIO/PARTILHA";
	public static final String FUNCIONALIDADE_GIA_SEPARACAO_ALTERAR = "ALTERAR GIA - ITCD SEPARAÇÃO/DIVÓRCIO/PARTILHA";
	 
	public static final int CODIGO_FUNCIONALIDADE_GIA_DOACAO_INCLUIR = 38;
	public static final int CODIGO_FUNCIONALIDADE_GIA_DOACAO_ALTERAR = 39;
	public static final int CODIGO_FUNCIONALIDADE_GIA_SEPARACAO_INCLUIR = 40;
	public static final int CODIGO_FUNCIONALIDADE_GIA_SEPARACAO_ALTERAR = 41;

	//VINCULAR DAR
	public static final String FUNCIONALIDADE_VINCULAR_DAR = "VINCULAR DAR A GIA-ITCD";
	
	public static final int CODIGO_FUNCIONALIDADE_VINCULAR_DAR = 42;
	
	//CONSULTAR GIA-ITCD
	public static final String FUNCIONALIDADE_GIA_ITCD_CONSULTAR = "CONSULTAR GIA - ITCD";
	public static final String FUNCIONALIDADE_GIA_INVENTARIO_ARROLAMENTO_CONSULTAR = "CONSULTAR GIA - ITCD INVENTÁRIO ARROLAMENTO";
	public static final String FUNCIONALIDADE_GIA_DOACAO_CONSULTAR = "CONSULTAR GIA - ITCD DOAÇÃO / OUTROS";
	public static final String FUNCIONALIDADE_GIA_SEPARACAO_CONSULTAR = "CONSULTAR GIA - ITCD SEPARAÇÃO/DIVÓRCIO/PARTILHA";
	
	public static final int CODIGO_FUNCIONALIDADE_GIA_ITCD_CONSULTAR = 43;
	public static final int CODIGO_FUNCIONALIDADE_GIA_INVENTARIO_ARROLAMENTO_CONSULTAR = 44;
	public static final int CODIGO_FUNCIONALIDADE_GIA_DOACAO_CONSULTAR = 45;
	public static final int CODIGO_FUNCIONALIDADE_GIA_SEPARACAO_CONSULTAR = 46;
	
	//ALTERAR GIA-ITCD
	 public static final String FUNCIONALIDADE_GIA_ITCD_ALTERAR = "ALTERAR GIA - ITCD";
	 
	 public static final int CODIGO_FUNCIONALIDADE_GIA_ITCD_ALTERAR = 47;
	
	
	//INATIVAR GIA-ITCD
	 public static final String FUNCIONALIDADE_GIA_ITCD_INATIVAR = "INATIVAR GIA - ITCD";
	 
	 public static final int CODIGO_FUNCIONALIDADE_GIA_ITCD_INATIVAR = 48;
	
	
	//REATIVAR GIA-ITCD
	 public static final String FUNCIONALIDADE_GIA_ITCD_REATIVAR = "REATIVAR GIA - ITCD";
	 
	 public static final int CODIGO_FUNCIONALIDADE_GIA_ITCD_REATIVAR = 49;
	
	
	//INCLUIR GIA-ITCD
	 public static final String FUNCIONALIDADE_GIA_ITCD_INCLUIR = "INCLUIR GIA-ITCD";
	 
	 public static final int CODIGO_FUNCIONALIDADE_GIA_ITCD_INCLUIR = 50;
	
	
	//ENVIAR SENHA GIA-ITCD
	 public static final String FUNCIONALIDADE_GIA_ITCD_SENHA_ENVIAR = "ENVIAR SENHA GIA - ITCD";
	 
	 public static final int CODIGO_FUNCIONALIDADE_GIA_ITCD_SENHA_ENVIAR = 51;
	
	
	//ENVIAR SENHA PESQUIASR CONTRIBUINTE
	 public static final String FUNCIONALIDADE_GIA_ITCD_SENHA_ENVIAR_CONTRIBUINTE_PESQUISAR = "ENVIAR SENHA PESQUISAR CONTRIBUINTE GIA - ITCD";
	 
	 public static final int CODIGO_FUNCIONALIDADE_GIA_ITCD_SENHA_ENVIAR_CONTRIBUINTE_PESQUISAR = 52;
	
		

}
