package br.gov.mt.sefaz.itc.util.dominio;

import br.com.abaco.util.dominio.util.AbstractDominioNumericoAbaco;


/**
 * Classe utilizada para informar o código da transação realizada pelo ATOR para o sistema de LOG.
 * @author Daniel Balieiro
 * @version $Revision: 1.2 $
 */
public class DomnCodigoTransacao extends AbstractDominioNumericoAbaco
{
	private static final long serialVersionUID = Long.MAX_VALUE;
	// <BEM>
	public static final int BEM_ALTERAR = 1;
	public static final int BEM_CANCELAR = 2;
	public static final int BEM_INCLUIR = 3;
	public static final int BEM_REATIVAR = 4;
	private static final String DESC_BEM_ALTERAR = "BEM ALTERAR";
	private static final String DESC_BEM_CANCELAR = "BEM CANCELAR";
	private static final String DESC_BEM_INCLUIR = "BEM INCLUIR";
	private static final String DESC_BEM_REATIVAR = "BEM REATIVAR";
	// </BEM>
	
	//<CULTURA>
	public static final int CULTURA_ALTERAR = 20;
	public static final int CULTURA_CANCELAR = 21;
	public static final int CULTURA_INCLUIR = 22;
	public static final int CULTURA_REATIVAR = 23;
	private static final String DESC_CULTURA_INCLUIR = "CULTURA INCLUIR";
	private static final String DESC_CULTURA_ALTERAR = "CULTURA ALTERAR";
	private static final String DESC_CULTURA_CANCELAR = "CULTURA CANCELAR";
	private static final String DESC_CULTURA_REATIVAR = "CULTURA REATIVAR";
	//</CULTURA>
	
	//<REBANHO>
	public static final int REBANHO_ALTERAR = 30;
	public static final int REBANHO_CANCELAR = 31;
	public static final int REBANHO_INCLUIR = 32;
	public static final int REBANHO_REATIVAR = 33;
	private static final String DESC_REBANHO_ALTERAR = "REBANHO ALTERAR";
	private static final String DESC_REBANHO_CANCELAR = "REBANHO CANCELAR";
	private static final String DESC_REBANHO_INCLUIR = "REBANHO INCLUIR";
	private static final String DESC_REBANHO_REATIVAR = "REBANHO REATIVAR";
	//</REBANHO>
	
	//<NATUREZAOPERACAO>
	public static final int NATUREZA_OPERACAO_INCLUIR = 40;
	public static final int NATUREZA_OPERACAO_ALTERAR = 41;
	public static final int NATUREZA_OPERACAO_REATIVAR = 42;
	//</NATUREZAOPERACAO>
	
	//<CONFIGURACAOGERENCIALPARAMETROS>
	public static final int CONFIGURACAO_GERENCIAL_PARAMETROS_INCLUIR = 50;
	public static final int CONFIGURACAO_GERENCIAL_PARAMETROS_ALTERAR = 51;
	private static final String DESC_CONFIGURACAO_GERENCIAL_PARAMETROS_INCLUIR =  "CONFIGURAÇÃO GERENCIAL PARAMETROS INCLUIR";
	private static final String DESC_CONFIGURACAO_GERENCIAL_PARAMETROS_ALTERAR = "CONFIGURAÇÃO GERENCIAL PARAMETROS ALTERAR";
	//</CONFIGURACAOGERENCIALPARAMETROS>
	
	//<BENFEITORIA>
	public static final int BENFEITORIA_ALTERAR = 60;
	public static final int BENFEITORIA_CANCELAR = 61;
	public static final int BENFEITORIA_INCLUIR = 62;
	public static final int BENFEITORIA_REATIVAR = 63;
	private static final String DESC_BENFEITORIA_ALTERAR = "BENFEITORIA ALTERAR";
	private static final String DESC_BENFEITORIA_CANCELAR = "BENFEITORIA CANCELAR";
	private static final String DESC_BENFEITORIA_INCLUIR = "BENFEITORIA INCLUIR";
	private static final String DESC_BENFEITORIA_REATIVAR = "BENFEITORIA REATIVAR";
	//</BENFEITORIA>
	
	//<CONSTRUCAO>
	public static final int CONSTRUCAO_ALTERAR = 70;
	public static final int CONSTRUCAO_CANCELAR = 71;
	public static final int CONSTRUCAO_INCLUIR = 72;
	public static final int CONSTRUCAO_REATIVAR = 73;
	private static final String DESC_CONSTRUCAO_ALTERAR = "CONSTRUCAO ALTERAR";
	private static final String DESC_CONSTRUCAO_CANCELAR = "CONSTRUCAO CANCELAR";
	private static final String DESC_CONSTRUCAO_INCLUIR = "CONSTRUCAO INCLUIR";
	private static final String DESC_CONSTRUCAO_REATIVAR = "CONSTRUCAO REATIVAR";
	//</CONSTRUCAO>
	
	//<MULTAMORA>
	public static final int MULTA_MORA_INCLUIR = 80;
	public static final int MULTA_MORA_ALTERAR = 81;
	private static final String DESC_MULTA_MORA_INCLUIR = "MULTA DE MORA INCLUIR";
	private static final String DESC_MULTA_MORA_ALTERAR = "MULTA DE MORA ALTERAR";
	//</MULTAMORA>
	
	//<PARAMETROLEGISLACAO>
	public static final int PARAMETRO_LEGISLACAO_ALTERAR = 90;
	public static final int PARAMETRO_LEGISLACAO_CANCELAR = 91;
	public static final int PARAMETRO_LEGISLACAO_INCLUIR = 92;
	public static final int PARAMETRO_LEGISLACAO_REATIVAR = 93;
	private static final String DESC_PARAMETRO_LEGISLACAO_ALTERAR = "PARAMETRO LEGISLAÇÃO ALTERAR";
	private static final String DESC_PARAMETRO_LEGISLACAO_CANCELAR = "PARAMETRO LEGISLAÇÃO CANCELAR";
	private static final String DESC_PARAMETRO_LEGISLACAO_INCLUIR = "PARAMETRO LEGISLAÇÃO INCLUIR";
	private static final String DESC_PARAMETRO_LEGISLACAO_REATIVAR = "PARAMETRO LEGISLAÇÃO REATIVAR";
	public static final int PARAMETRO_LEGISLACAO_INCLUIR_MULTA = 94;
	public static final int PARAMETRO_LEGISLACAO_EXCLUIR_MULTA = 95;
	private static final String DESC_PARAMETRO_LEGISLACAO_INCLUIR_MULTA = "PARAMETRO LEGISLAÇÃO INCLUIR MULTA";
	private static final String DESC_PARAMETRO_LEGISLACAO_EXCLUIR_MULTA = "PARAMETRO LEGISLAÇÃO EXCLUIR MULTA";
	public static final int PARAMETRO_LEGISLACAO_INCLUIR_ALIQUOTA = 96;
	public static final int PARAMETRO_LEGISLACAO_EXCLUIR_ALIQUOTA = 97;
	private static final String DESC_PARAMETRO_LEGISLACAO_INCLUIR_ALIQUOTA = "PARAMETRO LEGISLAÇÃO INCLUIR ALIQUOTA";
	private static final String DESC_PARAMETRO_LEGISLACAO_EXCLUIR_ALIQUOTA = "PARAMETRO LEGISLAÇÃO EXCLUIR ALIQUOTA";
	
	public static final int PARAMETRO_LEGISLACAO_ALTERAR_ALIQUOTA = 237;
	public static final int PARAMETRO_LEGISLACAO_ALTERAR_MULTA = 238;
	private static final String DESC_PARAMETRO_LEGISLACAO_ALTERAR_ALIQUOTA = "PARAMETRO LEGISLAÇÃO ALTERAR ALIQUOTA";
	private static final String DESC_PARAMETRO_LEGISLACAO_ALTERAR_MULTA = "PARAMETRO LEGISLAÇÃO ALTERAR MULTA";
	
	//</PAMETROLEGISLACAO>
	
	//<AJUDA>
	public static final int TELA_FUNCIONALIDADE_INCLUIR = 100;
	public static final int TELA_FUNCIONALIDADE_ALTERAR = 101;
	public static final int TELA_CAMPO_AJUDA_INCLUIR = 102;
	public static final int TELA_CAMPO_AJUDA_ALTERAR = 103;	
	private static final String DESC_TELA_CAMPO_AJUDA_INCLUIR = "TELA CAMPO AJUDA INCLUIR";
	private static final String DESC_TELA_CAMPO_AJUDA_ALTERAR = "TELA CAMPO AJUDA ALTERAR";
	private static final String DESC_TELA_FUNCIONALIDADE_INCLUIR = "TELA FUNCIONALIDADE INCLUIR";
	private static final String DESC_TELA_FUNCIONALIDADE_ALTERAR = "TELA FUNCIONALIDADE ALTERAR";
	//</AJUDA>
	
	//<GIA>
	public static final int GIA_ITCD_INCLUIR = 200;
	public static final int GIA_ITCD_ALTERAR = 201;
	public static final int GIA_ITCD_BEM_TRIBUTAVEL_INCLUIR = 202;
	public static final int GIA_ITCD_BEM_TRIBUTAVEL_ALTERAR = 203;
	public static final int GIA_ITCD_INVENTARIO_ARROLAMENTO_INCLUIR = 204;
	public static final int GIA_ITCD_INVENTARIO_ARROLAMENTO_BENEFICIARIO_INCLUIR = 205;
	public static final int GIA_ITCD_INVENTARIO_ARROLAMENTO_BENEFICIARIO_ALIQUOTA_INCLUIR = 206;
	public static final int GIA_ITCD_DOACAO_INCLUIR = 207;
	public static final int GIA_ITCD_DOACAO_BENEFICIARIO_INCLUIR = 208;
	public static final int GIA_ITCD_FICHA_IMOVEL_RURAL_INCLUIR = 209;
	public static final int GIA_ITCD_FICHA_IMOVEL_RURAL_CONSTRUCAO_INCLUIR = 210;
	public static final int GIA_ITCD_FICHA_IMOVEL_RURAL_BENFEITORIA_INCLUIR = 211;
	public static final int GIA_ITCD_FICHA_IMOVEL_RURAL_CULTURA_INCLUIR = 212;
	public static final int GIA_ITCD_FICHA_IMOVEL_RURAL_REBANHO_INCLUIR = 213;
	public static final int GIA_ITCD_FICHA_IMOVEL_URBANO_INCLUIR = 214;
	public static final int GIA_ITCD_FICHA_IMOVEL_URBANO_BENFEITORIA_INCLUIR = 215;
	public static final int GIA_ITCD_STATUS_INCLUIR = 216;
	public static final int GIA_ITCD_INVENTARIO_ARROLAMENTO_ALTERAR = 217;
	public static final int GIA_ITCD_INVENTARIO_ARROLAMENTO_BENEFICIARIO_ALTERAR = 218;
	public static final int GIA_ITCD_INVENTARIO_ARROLAMENTO_BENEFICIARIO_ALIQUOTA_ALTERAR = 219;
	public static final int GIA_ITCD_DOACAO_ALTERAR = 220;
	public static final int GIA_ITCD_DOACAO_BENEFICIARIO_ALTERAR = 221;
	public static final int GIA_ITCD_FICHA_IMOVEL_RURAL_ALTERAR = 222;
	public static final int GIA_ITCD_FICHA_IMOVEL_RURAL_CONSTRUCAO_ALTERAR = 223;
	public static final int GIA_ITCD_FICHA_IMOVEL_RURAL_BENFEITORIA_ALTERAR = 224;
	public static final int GIA_ITCD_FICHA_IMOVEL_RURAL_CULTURA_ALTERAR = 225;
	public static final int GIA_ITCD_FICHA_IMOVEL_RURAL_REBANHO_ALTERAR = 226;
	public static final int GIA_ITCD_FICHA_IMOVEL_URBANO_ALTERAR = 227;
	public static final int GIA_ITCD_FICHA_IMOVEL_URBANO_BENFEITORIA_ALTERAR = 228;
	public static final int GIA_ITCD_STATUS_ALTERAR = 229;
	public static final int GIA_ITCD_TEMPORARIO_INCLUIR = 230;
	public static final int GIA_ITCD_TEMPORARIO_ALTERAR = 231;
	public static final int GIA_ITCD_TEMPORARIO_DELETAR = 232;
	public static final int GIA_ITCD_SEPARACAO_INCLUIR = 233;
	public static final int GIA_ITCD_SEPARACAO_ALTERAR = 234;
	public static final int GIA_ITCD_SEPARACAO_CONJUGE_INCLUIR = 235;
	public static final int GIA_ITCD_SEPARACAO_CONJUGE_ALTERAR = 236;

	public static final String DESC_GIA_ITCD_INCLUIR = "GIA ITCD INCLUIR";
	public static final String DESC_GIA_ITCD_ALTERAR = "GIA ITCD ALTERAR";
	public static final String DESC_GIA_ITCD_BEM_TRIBUTAVEL_INCLUIR = "BEM TRIBUTAVEL INCLUIR";
	public static final String DESC_GIA_ITCD_BEM_TRIBUTAVEL_ALTERAR = "BEM TRIBUTAVEL ALTERAR";
	public static final String DESC_GIA_ITCD_INVENTARIO_ARROLAMENTO_INCLUIR = "GIA ITCD INVENTARIO ARROLAMENTO INCLUIR";
	public static final String DESC_GIA_ITCD_INVENTARIO_ARROLAMENTO_BENEFICIARIO_INCLUIR = "GIA ITCD INVENTARIO ARROLAMENTO BENEFICIARIO INCLUIR";
	public static final String DESC_GIA_ITCD_INVENTARIO_ARROLAMENTO_BENEFICIARIO_ALIQUOTA_INCLUIR = "GIA ITCD INVENTARIO ARROLAMENTO BENEFICIARIO ALIQUOTA INCLUIR";
	public static final String DESC_GIA_ITCD_DOACAO_INCLUIR = "GIA ITCD DOACAO INCLUIR";
	public static final String DESC_GIA_ITCD_DOACAO_BENEFICIARIO_INCLUIR = "GIA ITCD BENEFICIARIO INCLUIR";
	public static final String DESC_GIA_ITCD_FICHA_IMOVEL_RURAL_INCLUIR = "FICHA IMOVEL RURAL INCLUIR";
	public static final String DESC_GIA_ITCD_FICHA_IMOVEL_RURAL_CONSTRUCAO_INCLUIR = "FICHA IMOVEL RURAL CONSTRUCAO INCLUIR";
	public static final String DESC_GIA_ITCD_FICHA_IMOVEL_RURAL_BENFEITORIA_INCLUIR = "FICHA IMOVEL RURAL BENFEITORIA INCLUIR";
	public static final String DESC_GIA_ITCD_FICHA_IMOVEL_RURAL_CULTURA_INCLUIR = "FICHA IMOVEL RURAL CULTURA INCLUIR";
	public static final String DESC_GIA_ITCD_FICHA_IMOVEL_RURAL_REBANHO_INCLUIR = "FICHA IMOVEL RURAL REBANHO INCLUIR";
	public static final String DESC_GIA_ITCD_FICHA_IMOVEL_URBANO_INCLUIR = "FICHA IMOVEL URBANO INCLUIR";
	public static final String DESC_GIA_ITCD_FICHA_IMOVEL_URBANO_BENFEITORIA_INCLUIR = "FICHA IMOVEL URBANO BENFEITORIA INCLUIR";
	public static final String DESC_GIA_ITCD_STATUS_INCLUIR = "STATUS GIA INCLUIR";
	public static final String DESC_GIA_ITCD_INVENTARIO_ARROLAMENTO_ALTERAR = "GIA ITCD INVENTARIO ARROLAMENTO ALTERAR";
	public static final String DESC_GIA_ITCD_INVENTARIO_ARROLAMENTO_BENEFICIARIO_ALTERAR = "GIA ITCD INVENTARIO ARROLAMENTO BENEFICIARIO ALTERAR";
	public static final String DESC_GIA_ITCD_INVENTARIO_ARROLAMENTO_BENEFICIARIO_ALIQUOTA_ALTERAR = "GIA ITCD INVENTARIO ARROLAMENTO BENEFICIARIO ALIQUOTA ALTERAR";
	public static final String DESC_GIA_ITCD_DOACAO_ALTERAR = "GIA ITCD DOACAO ALTERAR";
	public static final String DESC_GIA_ITCD_DOACAO_BENEFICIARIO_ALTERAR = "GIA ITCD DOACAO BENEFICIARIO ALTERAR";
	public static final String DESC_GIA_ITCD_FICHA_IMOVEL_RURAL_ALTERAR = "FICHA IMOVEL RURAL ALTERAR";
	public static final String DESC_GIA_ITCD_FICHA_IMOVEL_RURAL_CONSTRUCAO_ALTERAR = "FICHA IMOVEL RURAL CONSTRUCAO ALTERAR";
	public static final String DESC_GIA_ITCD_FICHA_IMOVEL_RURAL_BENFEITORIA_ALTERAR = "FICHA IMOVEL RURAL BENFEITORIA ALTERAR";
	public static final String DESC_GIA_ITCD_FICHA_IMOVEL_RURAL_CULTURA_ALTERAR = "FICHA IMOVEL RURAL CULTURA ALTERAR";
	public static final String DESC_GIA_ITCD_FICHA_IMOVEL_RURAL_REBANHO_ALTERAR = "FICHA IMOVEL RURAL REBANHO ALTERAR";
	public static final String DESC_GIA_ITCD_FICHA_IMOVEL_URBANO_ALTERAR = "FICHA IMOVEL URBANO ALTERAR";
	public static final String DESC_GIA_ITCD_FICHA_IMOVEL_URBANO_BENFEITORIA_ALTERAR = "FICHA IMOVEL URBANO BENFEITORIA ALTERAR";
	public static final String DESC_GIA_ITCD_STATUS_ALTERAR = "STATUS GIA ALTERAR";
	public static final String DESC_GIA_ITCD_TEMPORARIO_INCLUIR = "GIA ITCD TEMPORARIO INCLUIR";
	public static final String DESC_GIA_ITCD_TEMPORARIO_ALTERAR = "GIA ITCD TEMPORARIO ALTERAR";
	public static final String DESC_GIA_ITCD_SEPARACAO_INCLUIR = "GIA ITCD SEPARACAO INCLUIR";
	public static final String DESC_GIA_ITCD_SEPARACAO_ALTERAR = "GIA ITCD SEPARACAO ALTERAR";
	public static final String DESC_GIA_ITCD_SEPARACAO_CONJUGE_INCLUIR = "GIA ITCD SEPARACAO CONJUGE INCLUIR";
	public static final String DESC_GIA_ITCD_SEPARACAO_CONJUGE_ALTERAR = "GIA ITCD SEPARACAO CONJUGE ALTERAR";
	public static final String DESC_GIA_ITCD_TEMPORARIO_DELETAR = "GIA_ITCD_TEMPORARIO_DELETAR";
	
	public static final int AVALIACAO_BEM_TRIBUTAVEL_INCLUIR = 300;
	public static final int AVALIACAO_SERVIDOR_INCLUIR =  301;
	public static final int AVALIACAO_BEM_TRIBUTAVEL_ALTERAR = 302;
	public static final int AVALIACAO_SERVIDOR_ALTERAR =  303;
	public static final int AVALIACAO_SERVIDOR_DELETAR = 304;
	
	public static final String DESC_AVALIACAO_BEM_TRIBUTAVEL_INCLUIR = "AVALIACAO BEM TRIBUTAVEL ALTERAR";
	public static final String DESC_AVALIACAO_SERVIDOR_INCLUIR = "AVALIACAO SERVIDOR ALTERAR";
	public static final String DESC_AVALIACAO_BEM_TRIBUTAVEL_ALTERAR = "AVALIACAO BEM TRIBUTAVEL ALTERAR";
	public static final String DESC_AVALIACAO_SERVIDOR_ALTERAR = "AVALIACAO SERVIDOR ALTERAR";
	public static final String DESC_AVALIACAO_SERVIDOR_DELETAR = "AVALIACAO SERVIDOR DELETAR";
	
	
	public static final int GIA_DAR_INCLUIR = 400;
	public static final int GIA_DAR_ALTERAR = 401;
	
	public static final String DESC_GIA_DAR_INCLUIR = "GIA DAR INCLUIR";
	public static final String DESC_GIA_DAR_ALTERAR = "GIA  DAR ALTERAR";
	
	private static int domnIndice[] = 
	  { BEM_ALTERAR, 
		BEM_CANCELAR, 
		BEM_INCLUIR, 
		BEM_REATIVAR, 
		BENFEITORIA_ALTERAR, 
		BENFEITORIA_CANCELAR, 
		BENFEITORIA_INCLUIR, 
		BENFEITORIA_REATIVAR, 
		CULTURA_ALTERAR, 
		CULTURA_CANCELAR, 
		CULTURA_INCLUIR, 
		CULTURA_REATIVAR, 
		REBANHO_ALTERAR, 
		REBANHO_CANCELAR, 
		REBANHO_INCLUIR, 
		REBANHO_REATIVAR, 
		NATUREZA_OPERACAO_INCLUIR, 
		NATUREZA_OPERACAO_ALTERAR, 
		NATUREZA_OPERACAO_REATIVAR, 
		CONSTRUCAO_ALTERAR, 
		CONSTRUCAO_CANCELAR, 
		CONSTRUCAO_INCLUIR, 
		CONSTRUCAO_REATIVAR, 
		PARAMETRO_LEGISLACAO_ALTERAR, 
		PARAMETRO_LEGISLACAO_CANCELAR, 
		PARAMETRO_LEGISLACAO_INCLUIR, 
		PARAMETRO_LEGISLACAO_REATIVAR, 
		PARAMETRO_LEGISLACAO_INCLUIR_MULTA, 
		PARAMETRO_LEGISLACAO_EXCLUIR_MULTA, 
		PARAMETRO_LEGISLACAO_INCLUIR_ALIQUOTA, 
		PARAMETRO_LEGISLACAO_EXCLUIR_ALIQUOTA, 
		MULTA_MORA_INCLUIR, 
		MULTA_MORA_ALTERAR, 
		CONFIGURACAO_GERENCIAL_PARAMETROS_INCLUIR,
		CONFIGURACAO_GERENCIAL_PARAMETROS_ALTERAR, 
		GIA_ITCD_INCLUIR, 
		GIA_ITCD_TEMPORARIO_INCLUIR,
		TELA_CAMPO_AJUDA_INCLUIR, 
		TELA_CAMPO_AJUDA_ALTERAR, 
		TELA_FUNCIONALIDADE_INCLUIR, 
		TELA_FUNCIONALIDADE_ALTERAR, 
		GIA_ITCD_INCLUIR,
		GIA_ITCD_ALTERAR,
		GIA_ITCD_BEM_TRIBUTAVEL_INCLUIR,
		GIA_ITCD_BEM_TRIBUTAVEL_ALTERAR,
		GIA_ITCD_INVENTARIO_ARROLAMENTO_INCLUIR,
		GIA_ITCD_INVENTARIO_ARROLAMENTO_BENEFICIARIO_INCLUIR,
		GIA_ITCD_INVENTARIO_ARROLAMENTO_BENEFICIARIO_ALIQUOTA_INCLUIR ,
		GIA_ITCD_DOACAO_INCLUIR,
		GIA_ITCD_DOACAO_BENEFICIARIO_INCLUIR,
		GIA_ITCD_FICHA_IMOVEL_RURAL_INCLUIR ,
		GIA_ITCD_FICHA_IMOVEL_RURAL_CONSTRUCAO_INCLUIR,
		GIA_ITCD_FICHA_IMOVEL_RURAL_BENFEITORIA_INCLUIR,
		GIA_ITCD_FICHA_IMOVEL_RURAL_CULTURA_INCLUIR,
		GIA_ITCD_FICHA_IMOVEL_RURAL_REBANHO_INCLUIR,
		GIA_ITCD_FICHA_IMOVEL_URBANO_INCLUIR ,
		GIA_ITCD_FICHA_IMOVEL_URBANO_BENFEITORIA_INCLUIR,
		GIA_ITCD_STATUS_INCLUIR ,
		GIA_ITCD_INVENTARIO_ARROLAMENTO_ALTERAR,
		GIA_ITCD_INVENTARIO_ARROLAMENTO_BENEFICIARIO_ALTERAR ,
		GIA_ITCD_INVENTARIO_ARROLAMENTO_BENEFICIARIO_ALIQUOTA_ALTERAR ,
		GIA_ITCD_DOACAO_ALTERAR ,
		GIA_ITCD_DOACAO_BENEFICIARIO_ALTERAR ,
		GIA_ITCD_FICHA_IMOVEL_RURAL_ALTERAR ,
		GIA_ITCD_FICHA_IMOVEL_RURAL_CONSTRUCAO_ALTERAR ,
		GIA_ITCD_FICHA_IMOVEL_RURAL_BENFEITORIA_ALTERAR ,
		GIA_ITCD_FICHA_IMOVEL_RURAL_CULTURA_ALTERAR ,
		GIA_ITCD_FICHA_IMOVEL_RURAL_REBANHO_ALTERAR ,
		GIA_ITCD_FICHA_IMOVEL_URBANO_ALTERAR ,
		GIA_ITCD_FICHA_IMOVEL_URBANO_BENFEITORIA_ALTERAR ,
		GIA_ITCD_STATUS_ALTERAR ,
		GIA_ITCD_TEMPORARIO_INCLUIR ,
		GIA_ITCD_TEMPORARIO_ALTERAR,
		GIA_ITCD_SEPARACAO_INCLUIR,
		GIA_ITCD_SEPARACAO_ALTERAR,
		GIA_ITCD_SEPARACAO_CONJUGE_INCLUIR,
		GIA_ITCD_SEPARACAO_CONJUGE_ALTERAR,
		GIA_ITCD_TEMPORARIO_DELETAR,
		AVALIACAO_BEM_TRIBUTAVEL_INCLUIR,
		AVALIACAO_SERVIDOR_INCLUIR,
		AVALIACAO_BEM_TRIBUTAVEL_ALTERAR,
		AVALIACAO_SERVIDOR_ALTERAR,
		AVALIACAO_SERVIDOR_DELETAR,
		GIA_DAR_INCLUIR,
		GIA_DAR_ALTERAR,
		PARAMETRO_LEGISLACAO_ALTERAR_ALIQUOTA,
		PARAMETRO_LEGISLACAO_ALTERAR_MULTA
		};
		
	private static String domnDescricao[] = 
	  { DESC_BEM_ALTERAR, 
		DESC_BEM_CANCELAR, 
		DESC_BEM_INCLUIR, 
		DESC_BEM_REATIVAR, 
		DESC_BENFEITORIA_ALTERAR, 
		DESC_BENFEITORIA_CANCELAR, 
		DESC_BENFEITORIA_INCLUIR, 
		DESC_BENFEITORIA_REATIVAR, 
		DESC_CULTURA_ALTERAR, 
		DESC_CULTURA_CANCELAR, 
		DESC_CULTURA_INCLUIR, 
		DESC_CULTURA_REATIVAR, 
		DESC_REBANHO_ALTERAR, 
		DESC_REBANHO_CANCELAR, 
		DESC_REBANHO_INCLUIR, 
		DESC_REBANHO_REATIVAR, 
		DESC_CONSTRUCAO_ALTERAR, 
		DESC_CONSTRUCAO_CANCELAR, 
		DESC_CONSTRUCAO_INCLUIR, 
		DESC_CONSTRUCAO_REATIVAR, 
		DESC_PARAMETRO_LEGISLACAO_ALTERAR, 
		DESC_PARAMETRO_LEGISLACAO_CANCELAR, 
		DESC_PARAMETRO_LEGISLACAO_INCLUIR, 
		DESC_PARAMETRO_LEGISLACAO_REATIVAR, 
		DESC_PARAMETRO_LEGISLACAO_INCLUIR_MULTA, 
		DESC_PARAMETRO_LEGISLACAO_EXCLUIR_MULTA, 
		DESC_PARAMETRO_LEGISLACAO_INCLUIR_ALIQUOTA, 
		DESC_PARAMETRO_LEGISLACAO_EXCLUIR_ALIQUOTA, 
		DESC_MULTA_MORA_INCLUIR, 
		DESC_MULTA_MORA_ALTERAR, 
		DESC_CONFIGURACAO_GERENCIAL_PARAMETROS_INCLUIR, 
		DESC_CONFIGURACAO_GERENCIAL_PARAMETROS_ALTERAR, 
		DESC_GIA_ITCD_INCLUIR, 
		DESC_GIA_ITCD_TEMPORARIO_INCLUIR, 
		DESC_TELA_CAMPO_AJUDA_INCLUIR, 
		DESC_TELA_CAMPO_AJUDA_ALTERAR, 
		DESC_TELA_FUNCIONALIDADE_INCLUIR, 
		DESC_TELA_FUNCIONALIDADE_ALTERAR,
		DESC_GIA_ITCD_INCLUIR,
		DESC_GIA_ITCD_ALTERAR ,
		DESC_GIA_ITCD_BEM_TRIBUTAVEL_INCLUIR ,
		DESC_GIA_ITCD_BEM_TRIBUTAVEL_ALTERAR ,
		DESC_GIA_ITCD_INVENTARIO_ARROLAMENTO_INCLUIR ,
		DESC_GIA_ITCD_INVENTARIO_ARROLAMENTO_BENEFICIARIO_INCLUIR ,
		DESC_GIA_ITCD_INVENTARIO_ARROLAMENTO_BENEFICIARIO_ALIQUOTA_INCLUIR ,
		DESC_GIA_ITCD_DOACAO_INCLUIR,
		DESC_GIA_ITCD_DOACAO_BENEFICIARIO_INCLUIR ,
		DESC_GIA_ITCD_FICHA_IMOVEL_RURAL_INCLUIR ,
		DESC_GIA_ITCD_FICHA_IMOVEL_RURAL_CONSTRUCAO_INCLUIR,
		DESC_GIA_ITCD_FICHA_IMOVEL_RURAL_BENFEITORIA_INCLUIR ,
		DESC_GIA_ITCD_FICHA_IMOVEL_RURAL_CULTURA_INCLUIR ,
		DESC_GIA_ITCD_FICHA_IMOVEL_RURAL_REBANHO_INCLUIR ,
		DESC_GIA_ITCD_FICHA_IMOVEL_URBANO_INCLUIR ,
		DESC_GIA_ITCD_FICHA_IMOVEL_URBANO_BENFEITORIA_INCLUIR ,
		DESC_GIA_ITCD_STATUS_INCLUIR ,
		DESC_GIA_ITCD_INVENTARIO_ARROLAMENTO_ALTERAR ,
		DESC_GIA_ITCD_INVENTARIO_ARROLAMENTO_BENEFICIARIO_ALTERAR ,
		DESC_GIA_ITCD_INVENTARIO_ARROLAMENTO_BENEFICIARIO_ALIQUOTA_ALTERAR ,
		DESC_GIA_ITCD_DOACAO_ALTERAR ,
		DESC_GIA_ITCD_DOACAO_BENEFICIARIO_ALTERAR ,
		DESC_GIA_ITCD_FICHA_IMOVEL_RURAL_ALTERAR ,
		DESC_GIA_ITCD_FICHA_IMOVEL_RURAL_CONSTRUCAO_ALTERAR ,
		DESC_GIA_ITCD_FICHA_IMOVEL_RURAL_BENFEITORIA_ALTERAR ,
		DESC_GIA_ITCD_FICHA_IMOVEL_RURAL_CULTURA_ALTERAR ,
		DESC_GIA_ITCD_FICHA_IMOVEL_RURAL_REBANHO_ALTERAR ,
		DESC_GIA_ITCD_FICHA_IMOVEL_URBANO_ALTERAR ,
		DESC_GIA_ITCD_FICHA_IMOVEL_URBANO_BENFEITORIA_ALTERAR ,
		DESC_GIA_ITCD_STATUS_ALTERAR ,
		DESC_GIA_ITCD_TEMPORARIO_INCLUIR ,
		DESC_GIA_ITCD_TEMPORARIO_ALTERAR,
		DESC_GIA_ITCD_SEPARACAO_INCLUIR,
		DESC_GIA_ITCD_SEPARACAO_ALTERAR,
		DESC_GIA_ITCD_SEPARACAO_CONJUGE_INCLUIR,
		DESC_GIA_ITCD_SEPARACAO_CONJUGE_ALTERAR,
		DESC_GIA_ITCD_TEMPORARIO_DELETAR,
		DESC_AVALIACAO_BEM_TRIBUTAVEL_INCLUIR,
		DESC_AVALIACAO_SERVIDOR_INCLUIR ,
		DESC_AVALIACAO_BEM_TRIBUTAVEL_ALTERAR,
		DESC_AVALIACAO_SERVIDOR_ALTERAR,
		DESC_AVALIACAO_SERVIDOR_DELETAR,
		DESC_GIA_DAR_INCLUIR,
		DESC_GIA_DAR_ALTERAR,
		DESC_PARAMETRO_LEGISLACAO_ALTERAR_ALIQUOTA,
		DESC_PARAMETRO_LEGISLACAO_ALTERAR_MULTA
	  };

	/**
	 * Instancia o domínio sem valor corrente
	 */
	public DomnCodigoTransacao()
	{
		super(-1);
	}

	/**
	 * Instancia o domínio com o valor corrente do domínio de acordo com a constante informada.
	 * @param  valorConstante O valor do domínio.
	 */
	public DomnCodigoTransacao(int valorConstante)
	{
		super(valorConstante);
	}

	/**
	 * Obtém o array com todas as constantes deste domínio.
	 * <b>Este método é utilizado pelo tagsgenerico.jar, logo é obrigatório para todos os domínios.</b>
	 * @return int[] - array de inteiro com as constantes deste domínio.
	 */
	public int[] getDomnIndice()
	{
		return domnIndice;
	}

	/**
	 * Obtém o array com todas as descrições das constantes deste domínio.
	 * <b>Este método é utilizado pelo tagsgenerico.jar, logo é obrigatório para todos os domínios.</b>
	 * @return String[] - array de String com as constantes deste domínio.
	 */
	public String[] getDomnDescricao()
	{
		return domnDescricao;
	}

	public int getKey()
	{
		return super.getValorCorrente();
	}	
}

